#API returns
swagger: '2.0'
#host:
info:
  title: API Возвраты товаров баллами
  version: 0.0.1
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
consumes:
  - application/json
paths:
  /api/v1/returns {channel}, {card_id}:
    get:
      summary: Проверка доступности возвратов
      parameters:
        - name: channel
          in: path
          required: true
          type: integer
          format: int32
          description: Идентификатор канала (МП) #Для проверки доступности канала
        - name: card_id 
          in: path
          required: true
          type: string
          description: Уникальный номер карты #Для проверки наличия пользователя в черном списке, можно убрать в другой запрос
      tags:
        - returns
      responses:
        default:
           description: Unexpected error #Нужно ли отлавливать такие ошибки?
        '200':
          description: Канал МП доступен для возвратов
        '403': 
          description: |
            'Возвраты недоступны для всей сети'
              code: 4031
            'Возвраты недоступны для МП'
              code: 4032  
            'Возвраты недоступны для карты {card_id}'
              code: 4033 
        '404':
          description: '({card_id}) не найден'
        '422':
          description: 'Bad Request/Unprocessable Entity'   
        '503':
          description: Сервис недоступен

  /api/v1/returns/return {channel}:
    get:
      summary: Проверка доступности возвратов и получение лимитов
      parameters:
        - name: channel
          in: path
          required: true
          type: integer
          format: int32
        - name: return
          in: query
          required: true
          schema:
              $ref: '#/definitions/return'
      tags: 
        - returns
      responses:
        '200':
          description: 'Возврат доступен'
          schema:
            $ref: '#/definitions/return_check'    
        '403': 
          description: |
            'Возвраты недоступны для всей сети'
              code: 4031
            'Возвраты недоступны для МП'
              code: 4032  
            'Возвраты недоступны для карты {card_id}'
              code: 4033   
        '404':
          description: 'Не найден один из параметров запроса' 
          schema:
            $ref: '#/definitions/return_check'    
        '415':
          description: 
            'Unsupported Media Type' #Нужно ли отлавливать такие ошибки?
        '422':
          description: 'Bad Request/Unprocessable Entity'      
        '429':
          description:
            'Too Many Requests'          #Нужно ли отлавливать такие ошибки?
        '503':
          description: Сервис недоступен
                    
  /api/v1/returns/ticket:  
    post:
      summary: Отправка данных для возврата
      parameters:
        - name: ticket_return
          in: body
          required: true
          schema:
            $ref: '#/definitions/ticket_return'
      responses:
        default:
           description: Unexpected error
        '200':
          description: 'Данные для возврата отправлены'   
        '415':
          description: 
            'Unsupported Media Type'
        '429':
          description:
            'Too Many Requests'           
        

definitions:

  return:
    type: object
    required:
      - transaction_id # Также нужна дата
      - card_id
      - sap_code
    properties:
      transaction_id:
        description: Идентификатор транзакции #Для проверки доступности возвратов по чеку, с учетом даты
        type: string
        #maxLength: 0
        #pattern: 
      card_id:
        description: Идентификатор карты #Для проверки и получения лимитов по Пользователю
        type: string
        #maxLength: 0
        #pattern: 
      sap_code:
        description: Идентификатор магазина #Для проверки и получения лимитов по магазину
        type: string
        #maxLength: 0
        #pattern: 
      plu:
        description: Код товара #Для проверки принадлежности к возвратной категории  
        type: integer
        # minLength:
        # maxLength: 
        # format:    

  ticket_return:
      type: object
      required:
          - transaction_id
          - card_id
          - sap_code
          - goods
      properties:
          transaction_id: 
            description: Идентификатор транзакции #Для проверки доступности возвратов по чеку, с учетом даты
            type: string
            #maxLength: 0
            #pattern: 
          card_id: 
            description: Идентификатор карты #Для проверки и получения лимитов по Пользователю
            type: string
            #maxLength: 0
            #pattern: 
          sap_code:
            description: Идентификатор магазина #Для проверки и получения лимитов по магазину
            type: string
            #maxLength: 0
            #pattern: 
          goods: #список товаров на возврат
            type: array
           # maxLength: 0
            items:
                $ref: '#/definitions/return_goods'
                
  return_goods:
    type: object
    required:
      - plu
      - count
      - price #в случае возможности получения данных по транзакции - данный параметр не нужен.
      - url_photo
      - reason_id 
    properties:
      plu:
        description: идентификатор товара
        type: string
      count:
        description: Количество товара на возврат
        type: integer
        format: int32
      price:
        type: integer
        format: int32
      url_photo: #Большой вопрос - как и где хранить фото
        description: Адрес к изображению (url)
        type: string
        # minLength:
        # maxLength: 
        # pattern:
      reason_id:
        description: Идентификатор причины возврата
        items:
          $ref: 'return_reason'

      return_reason:
        type: object
        required:
          - reason_id
        properties:  
          reason_id:    
            description: Идентификатор причины возврата
            type: string
          reason_text:
            description: 'Текст причины возврата'
            type: string
            format: byte  

  return_check:
    type: object
    properties:
      transaction_check:
        description: 'По {transaction_id} доступен возврат'
        type: string
      store_check:
        description: 'По магазину {sap_code} доступен лимит {store_limit}' 
        type: string
      card_check:  
        description: 'По карте {card_id} доступен лимит возврата на сумму {card_limit}'
        type: string
      goods_check: 
        description: 'Статус возврата для {plu} = {product_return_status}'
        type: array
        items:
          $ref: '#/definitions/goods_check'

  goods_check:
    type: object
    required:
      - plu
      - product_return_status
    properties:
      plu:
        description: идентификатор товара
        type: string
      product_return_status:
        description: Соответствие возвратной категории   #не знаю как реализовано, предлагаю 0 - Недоступен возврат, 1 доступен полный, 2 - доступен частичный(н-р весовой товар)
        type: integer
        format: int32
             
                
#securityDefinitions:   
...                 
          
